version: '3'
services:
  redis:
    image: redis:6
    volumes:
      - redis-data:/data
  web:
    build: .
    command: python -m sonar_agent.main web
    ports:
      - "5000:5000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - REPO_NAME=${REPO_NAME}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
    restart: always
  worker:
    build: .
    command: python -m sonar_agent.main worker
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - REPO_NAME=${REPO_NAME}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
    restart: always
    deploy:
      replicas: 3
volumes:
  redis-data: